services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile

    container_name: nextask_server

    restart: unless-stopped

    env_file:
      - server/.env.production

    ports:
      - '3000:3000'

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile

    container_name: nextask_client

    restart: unless-stopped

    env_file:
      - client/.env.production

    ports:
      - '80:80'

    depends_on:
      - server
