// server/src/index.ts
import "dotenv/config";
import express, { Request, Response, NextFunction } from "express";
import cors from "cors";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./generated/routes"; // generated by TSOA
import swaggerDocument from "./generated/swagger.json"; // generated by TSOA

const app = express();
const PORT = parseInt(process.env.PORT ?? "3000", 10);

// ─── Core middleware ──────────────────────────────────────────────────────────
app.use(
  cors({
    origin: process.env.CLIENT_ORIGIN ?? "http://localhost:5173",
    credentials: true,
  })
);
app.use(express.json());

// ─── Swagger docs ─────────────────────────────────────────────────────────────
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// ─── TSOA-generated routes ────────────────────────────────────────────────────
RegisterRoutes(app);

// ─── 404 handler ─────────────────────────────────────────────────────────────
app.use((_req: Request, res: Response) => {
  res.status(404).json({ message: "Route not found." });
});

// ─── Global error handler ─────────────────────────────────────────────────────
app.use((err: unknown, _req: Request, res: Response, _next: NextFunction) => {
  const error = err as {
    status?: number;
    message?: string;
    errors?: unknown;
    fields?: unknown;
  };

  // TSOA validation errors come with `fields`
  if (error.fields) {
    res.status(422).json({
      message: "Validation failed",
      errors: error.fields,
    });
    return;
  }

  const status = error.status ?? 500;
  const message = error.message ?? "Internal server error";
  res.status(status).json({ message, ...(error.errors ? { errors: error.errors } : {}) });
});

// ─── Start ────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`🚀 nexTask server running on http://localhost:${PORT}`);
  console.log(`📖 Swagger docs: http://localhost:${PORT}/api-docs`);
});

export default app;
